# Generated by Django 4.0.5 on 2022-06-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsblog',
            old_name='context',
            new_name='content',
        ),
        migrations.AddField(
            model_name='newsblog',
            name='user_comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsblog',
            name='image',
            field=models.ImageField(upload_to='NewBlogThumbnail'),
        ),
    ]
