# Generated by Django 4.0.5 on 2022-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_paymentmethod_donation_cause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=models.ImageField(blank=True, default='default_gleiche_banner_image.jpg', upload_to='Causes'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='image',
            field=models.ImageField(blank=True, default='default_gleiche_logo.png', upload_to='ExecutivesImages'),
        ),
        migrations.AlterField(
            model_name='newsblog',
            name='image',
            field=models.ImageField(blank=True, default='default_gleiche_banner_image.jpg', upload_to='NewBlogThumbnail'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, default='default_gleiche_banner_image.jpg', upload_to='Slides'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(blank=True, default='default_gleiche_banner_image.jpg', upload_to='Sponsors'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='default_gleiche_logo.png', upload_to='TestimonialUserImages'),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='image',
            field=models.ImageField(blank=True, default='default_gleiche_banner_image.jpg', upload_to='UpcomingEvents'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, default='default_gleiche_logo.png', upload_to='VolunteerUserImages'),
        ),
    ]
