# Generated by Django 4.0.5 on 2022-06-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_newsblog_allow_public_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblog',
            name='image',
            field=models.ImageField(null=True, upload_to='NewBlogThumbnail'),
        ),
    ]
