# Generated by Django 4.0.5 on 2022-08-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_newsblog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsblog',
            options={'verbose_name': 'news_blog', 'verbose_name_plural': 'news_blogs'},
        ),
        migrations.AlterField(
            model_name='newsblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='NewBlogThumbnail'),
        ),
    ]
