# Generated by Django 4.0.5 on 2022-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_newsblog_options_alter_newsblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblog',
            name='user_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
