# Generated by Django 4.0.5 on 2022-08-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_newsblog_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblog',
            name='image',
            field=models.ImageField(blank=True, default='default_news_image.jpg', upload_to='NewBlogThumbnail'),
        ),
    ]
