# Generated by Django 4.0.5 on 2022-08-15 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_newsblog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='info',
            new_name='occupation',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='default_user_image.jpg', upload_to='Testimonials'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimony',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
