# Generated by Django 4.0.5 on 2022-08-15 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_info_testimonial_occupation_testimonial_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
