# Generated by Django 4.0.5 on 2022-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_testimonial_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='default_user_image.png', upload_to='Testimonials'),
        ),
    ]
