# Generated by Django 4.0.5 on 2022-09-04 10:52

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsblog',
            options={'ordering': ('-date_created',), 'verbose_name': 'news_blog', 'verbose_name_plural': 'news_blogs'},
        ),
        migrations.AddField(
            model_name='newsblog',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title', unique_with=['id']),
            preserve_default=False,
        ),
    ]
