# Generated by Django 4.0.5 on 2022-09-04 11:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_newsblog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblog',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('date_created__month',)),
        ),
    ]
